
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xp-portfolio
spec:
  rules:
  - host: xp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: xp-portfolio
            port:
              number: 80
