
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xp-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xp-portfolio
  template:
    metadata:
      labels:
        app: xp-portfolio
    spec:
      containers:
      - name: web
        image: nginx:1.25
        ports:
        - containerPort: 80
