
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xp-portfolio.fullname" . }}
spec:
  selector:
    app: {{ include "xp-portfolio.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  type: {{ .Values.service.type }}
