
name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Lint repo
        run: echo "Run flake8/ruff here if needed"
      - name: Terraform fmt & validate (no creds)
        uses: hashicorp/setup-terraform@v3
      - run: |
          cd terraform/aws-infra
          terraform fmt -check
          terraform validate
      - name: Build Flask example image
        run: |
          docker build -t xp-portfolio:dev docker/examples/flask_app
